spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false

    fetchRegistry: false
    eureka-server-connect-timeout-seconds: 60
    eureka-service-url-poll-interval-seconds: 15
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    prefer-same-zone-eureka: true
    healthcheck:
      enabled: true
  server:
        expected-client-Renewal-interval-seconds: 20
  instance:
    lease-expiration-duration-in-seconds: 70

    #задача 3.3.6
  #	не хотим получать информацию реестра от Eureka Server;
  #	время ожидания (одна минута) до истечения тайм-аута соединения с Eureka Server;
  #	каждые 15 секунд запрашивать изменения об информации с сервера;
  #	запрети dns и укажи явный маршрут к серверам eureka (serviceUrl);
  #	если возникнут проблемы в сети или наш сервер выйдет из строя, мы хотим запретить клиент;
  #	использовать сервер eureka в той же зоне;
  #	для клиента включим healthcheck;
  #	установить время, по которому сервер будет ожидать эхо запрос от клиента о том, что он жив (20 секунд);
  #	если Eureka Server не видел обновления в течение 70 секунд, он удаляет экземпляр из своего реестра.
